spring:
  application:
    name: rabbitmq-demo
  rabbitmq:
    host: 192.168.211.133
    port: 5672
    username: root
    password: myroot
    virtual-host: /vhost_root
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true # 该参数为true的时候消息如果没路由到相应的队列，会返回给生产者