spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.4:3306/mybatis-plus-demo?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10