spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: myroot
    url: jdbc:mysql://localhost:3306/mybatis-plus-demo?useSSL=false&serverTimezone=GMT%2B8
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10