server:
  port: 18081
spring:
  redis:
    host: 192.168.1.4
    port: 6379
    password: myroot
    database: 0
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: 1000 # 连接池最大阻塞等待时间
      shutdown-timeout: 100 # 关闭超时