server:
  port: 18080
spring:
  redis:
    host: 120.78.131.194
    port: 6379
    password: 202330Re
    database: 0
    lettuce:
      pool:
        max-active: 10
        min-idle: 2
        max-idle: 8
        max-wait: 1000 # 连接池最大阻塞等待时间
      shutdown-timeout: 20000 # 关闭超时