server:
  port: 18081
spring:
  redis:
    host: 192.168.1.4
    port: 6379
    password: myroot
    database: 0
    jedis:
      pool:
        max-active: 10
        min-idle: 2
        max-idle: 8
    timeout: 2000