server:
  port: 18080
spring:
  redis:
    #host: 192.168.1.4
    #password: myroot
    host: 120.78.131.194
    password: 202330Re
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 10
        min-idle: 2
        max-idle: 8
    timeout: 2000